spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heam?userUnicode=true&characterEncoding=utf8&useSSL=false
    username: bps
    password: 123456
    maxIdleTiem: 60
    initialPoolSize: 8
    minPoolSize: 5
    maxPoolSize: 20

#server:
#  servlet:
#    context-path: .

mybatis:
  type-aliases-package: cn.bps.heam.domain.model
  mapper-locations: classpath:mappers/*.xml

